#!/usr/bin/env python
"""
stage2_obs_validation.py

Observation-side validation of the Stage-2 memory and the Stage-2c timing.

Stage-2 reads memory off the CALIBRATED MODEL's flow (tau_Qsim) and Stage-2c reads
the snowmelt phase shift off the same simulated series. Both are therefore, on their
own, statements about HBV rather than about the catchments. The recession-constant
check in Stage-2 does not fix this: the LZ series is *generated by* K2, so recovering
K2 from it tests the ACF estimator, not the hydrology.

This script recomputes both properties on the OBSERVED discharge (flow_obs, already
carried in the state frames) so the model-derived quantities can be compared against
the data that constrained them:

  tau_Qobs / ac1_Qobs        memory of observed flow
  tau_Qsim_m / ac1_Qsim_m    memory of simulated flow MASKED to the observed record,
                             so the comparison is like-for-like and any difference is
                             model-vs-observation rather than gap-structure
  reg_lag_obs / late_frac_obs / winter_r_obs / sig_obs
                             the Stage-2c timing profile, driven by the same Stage-1
                             fitted winter forcing but read off observed flow
  retention_obs              share of the early (Dec-Jun) response energy arriving in
                             March or later, the Stage-2c one-sided duration metric read
                             off observed flow. This is the test that intrinsic memory
                             governs how long the FORCED anomaly lasts; see the
                             stage2c_registration_lag.py docstring for why the window is
                             one-sided, and Text S2 of the manuscript for the result.

Observed discharge is gappy (median ~63 %% coverage, minimum 10 yr), so the ACF here is
PAIRWISE-COMPLETE: the autocovariance at lag k uses only the day pairs where both ends
are present. Compacting the finite values (as is safe for the gap-free simulated series)
would splice non-adjacent days together and bias the ACF toward short memory.

    python stage2_obs_validation.py --states-dir <dir> --manifest <m.csv> \
        --stage1 <stage1_DJF.parquet> --indices <teleconnection_seasonal.csv> \
        --stage2 <stage2_DJF.parquet> --stage2c <stage2c_DJF.parquet> \
        --out <stage2_obs_DJF.parquet>
    python stage2_obs_validation.py --selftest
"""
from __future__ import annotations
import argparse
import glob
import os

import numpy as np
import pandas as pd

KMAX = 1825          # e-folding search horizon (~5 yr), as Stage-2
MIN_DAYS = 3000      # valid observed days needed for a stable ACF
MIN_PAIRS = 365      # valid day-pairs needed at a lag before its ACF value is used
MIN_MONTH_DAYS = 20  # valid days needed before a calendar month gets a mean
MIN_WINTERS = 20     # winters needed for a per-lag correlation, as Stage-2c

BETA = {"NAO_DJF": "beta_NAO", "EA_DJF": "beta_EA",
        "EAWR_DJF": "beta_EAWR", "SCA_DJF": "beta_SCA"}
LAGS = list(range(0, 12))
LATE = 4
RET_FROM = 3         # retention numerator starts at L=3 (March), as Stage-2c
RET_TO = 6           # retention window ends at L=6 (June), inclusive: one-sided, so the
                     # L~6-8 melt peak cannot inflate a duration metric with timing


# --------------------------------------------------------------------------- memory

def deseasonalize_detrend_nan(s: pd.Series) -> np.ndarray:
    """Remove day-of-year climatology then a linear trend, PRESERVING gaps as NaN.

    Stage-2's version compacts the finite values; here the NaN positions have to
    survive so the pairwise-complete ACF below knows which lags are real."""
    a = s.to_numpy(dtype=float)
    doy = s.index.dayofyear.to_numpy()
    fin = np.isfinite(a)
    if fin.sum() < MIN_DAYS:
        return np.full(a.size, np.nan)
    sums = np.bincount(doy, weights=np.where(fin, a, 0.0), minlength=367)
    cnts = np.bincount(doy, weights=fin.astype(float), minlength=367)
    clim = sums / np.maximum(cnts, 1.0)
    out = np.where(fin, a - clim[doy], np.nan)
    t = np.arange(a.size, dtype=float)
    b1, b0 = np.polyfit(t[fin], out[fin], 1)
    out[fin] -= b0 + b1 * t[fin]
    return out


def acf_gapaware(a: np.ndarray, kmax: int = KMAX):
    """Pairwise-complete ACF of a gappy series, by FFT.

    At lag k the autocovariance is the mean of x_i * x_{i+k} over the pairs where
    BOTH ends are observed. Zero-filling the anomaly gives the numerator and
    zero-filling the finite-mask gives the pair count, both as autocorrelations."""
    fin = np.isfinite(a)
    if fin.sum() < MIN_DAYS:
        return None, None
    x = np.where(fin, a - a[fin].mean(), 0.0)
    m = fin.astype(float)
    n = x.size
    size = 1 << int(np.ceil(np.log2(2 * n)))
    fx = np.fft.rfft(x, size)
    fm = np.fft.rfft(m, size)
    num = np.fft.irfft(fx * np.conj(fx))[: kmax + 1].real
    cnt = np.fft.irfft(fm * np.conj(fm))[: kmax + 1].real
    cnt = np.round(cnt)
    if cnt[0] < MIN_DAYS or num[0] <= 0:
        return None, None
    acov = np.where(cnt >= MIN_PAIRS, num / np.maximum(cnt, 1.0), np.nan)
    if not np.isfinite(acov[0]) or acov[0] <= 0:
        return None, None
    return acov / acov[0], cnt


def efolding_from_acf(acf: np.ndarray) -> float:
    """First crossing of 1/e, linearly interpolated. inf = censored, nan = degenerate."""
    if acf is None:
        return np.nan
    thr = 1.0 / np.e
    below = np.where(np.isfinite(acf) & (acf < thr))[0]
    if below.size == 0:
        return np.inf
    k = int(below[0])
    if k == 0:
        return 0.0
    a0, a1 = acf[k - 1], acf[k]
    if not np.isfinite(a0):
        return np.nan
    frac = (a0 - thr) / (a0 - a1) if a0 != a1 else 0.0
    return (k - 1) + frac


def memory_metrics(s: pd.Series, tag: str) -> dict:
    a = deseasonalize_detrend_nan(s)
    acf, cnt = acf_gapaware(a)
    tau = efolding_from_acf(acf)
    ac1 = float(acf[1]) if (acf is not None and np.isfinite(acf[1])) else np.nan
    return {f"tau_{tag}": np.nan if not np.isfinite(tau) else float(tau),
            f"cens_{tag}": bool(np.isinf(tau)),
            f"ac1_{tag}": ac1,
            f"ndays_{tag}": int(np.isfinite(a).sum())}


# --------------------------------------------------------------------------- timing

def monthly_anom_gapaware(q: pd.Series) -> pd.Series:
    """Monthly-mean flow anomaly, requiring MIN_MONTH_DAYS observed days per month."""
    g = q.resample("MS")
    m = g.mean()
    m = m.where(g.count() >= MIN_MONTH_DAYS)
    clim = m.groupby(m.index.month).transform("mean")
    return m - clim


def lag_profile(ma: pd.Series, phat: pd.Series):
    r = np.full(len(LAGS), np.nan)
    nL = np.zeros(len(LAGS), dtype=int)
    idx = {(t.year, t.month): v for t, v in ma.items()}
    for j, L in enumerate(LAGS):
        xs, ys = [], []
        for y, p in phat.items():
            if not np.isfinite(p):
                continue
            dt = pd.Timestamp(int(y) - 1, 12, 1) + pd.DateOffset(months=L)
            v = idx.get((dt.year, dt.month), np.nan)
            if np.isfinite(v):
                xs.append(v)
                ys.append(p)
        nL[j] = len(xs)
        if len(xs) >= MIN_WINTERS and np.std(xs) > 0 and np.std(ys) > 0:
            r[j] = np.corrcoef(xs, ys)[0, 1]
    return r, nL


def timing_metrics(r: np.ndarray, nL: np.ndarray, suffix: str) -> dict:
    keys = ["reg_lag", "late_frac", "winter_r", "peak_lag", "sig", "retention", "n_lags"]
    nan = {f"{k}{suffix}": np.nan for k in keys}
    fin = np.isfinite(r)
    nan[f"n_lags{suffix}"] = int(fin.sum())
    if fin.sum() < 6:
        return nan
    L = np.array(LAGS, dtype=float)
    w = np.clip(np.where(fin, r ** 2 - 1.0 / np.maximum(nL - 2, 1), 0.0), 0, None)
    W = w.sum()
    if W <= 0:
        return nan
    win = fin & (L <= 2)
    early = w[L <= RET_TO].sum()
    return {f"reg_lag{suffix}": float((L * w).sum() / W),
            f"late_frac{suffix}": float(w[L >= LATE].sum() / W),
            f"winter_r{suffix}": float(np.nanmean(r[win])) if win.any() else np.nan,
            f"peak_lag{suffix}": int(L[np.nanargmax(np.abs(np.where(fin, r, np.nan)))]),
            f"sig{suffix}": float(np.nanmax(np.abs(r[fin]))),
            f"retention{suffix}": (float(w[(L >= RET_FROM) & (L <= RET_TO)].sum() / early)
                                   if early > 0 else np.nan),
            f"n_lags{suffix}": int(fin.sum())}


# --------------------------------------------------------------------------- driver

def run(states_dir, manifest_path, stage1, indices):
    man = pd.read_csv(manifest_path).set_index("gauge_id")
    spinup = pd.to_datetime(man["spinup_end"])
    betas = stage1.set_index("gauge_id")
    rows = []
    files = sorted(glob.glob(os.path.join(states_dir, "*", "*.parquet")))
    for i, f in enumerate(files, 1):
        gid = os.path.basename(f)[: -len(".parquet")]
        src = os.path.basename(os.path.dirname(f))
        if gid not in betas.index:
            continue
        df = pd.read_parquet(f, columns=["flow_obs", "Qsim"])
        if gid in spinup.index:
            df = df[df.index >= spinup.loc[gid]]
        obs = df["flow_obs"]
        sim_masked = df["Qsim"].where(obs.notna())    # like-for-like sampling

        rec = {"gauge_id": gid, "source": src}
        rec.update(memory_metrics(obs, "Qobs"))
        rec.update(memory_metrics(sim_masked, "Qsim_m"))

        b = betas.loc[gid]
        phat = sum(b[BETA[c]] * indices[c] for c in BETA).dropna()
        r_o, n_o = lag_profile(monthly_anom_gapaware(obs), phat)
        rec.update(timing_metrics(r_o, n_o, "_obs"))

        rows.append(rec)
        if i % 500 == 0:
            print(f"  {i}/{len(files)} catchments processed", flush=True)
    return pd.DataFrame(rows)


def validate(res: pd.DataFrame, stage2: pd.DataFrame, stage2c: pd.DataFrame):
    from scipy import stats
    d = res.merge(stage2[["gauge_id", "tau_Qsim", "ac1_Qsim", "sp_active_frac", "tau_LZ"]],
                  on="gauge_id", how="left")
    d = d.merge(stage2c[["gauge_id", "reg_lag", "late_frac", "sig"]],
                on="gauge_id", how="left")

    print("\n=== MEMORY: observed vs simulated flow ===", flush=True)
    print(f"catchments with a resolvable observed memory: "
          f"{int(np.isfinite(d.tau_Qobs).sum())} of {len(d)}", flush=True)
    for col, lab in [("tau_Qobs", "tau observed"), ("tau_Qsim_m", "tau simulated (masked)"),
                     ("tau_Qsim", "tau simulated (full)")]:
        s = d[col].dropna()
        print(f"  {lab:24s} median {s.median():7.2f} d   IQR {s.quantile(.25):6.2f}"
              f"-{s.quantile(.75):7.2f}", flush=True)
    for a, b, lab in [("tau_Qobs", "tau_Qsim_m", "tau  obs vs sim(masked)"),
                      ("tau_Qobs", "tau_Qsim", "tau  obs vs sim(full)  "),
                      ("ac1_Qobs", "ac1_Qsim_m", "ac1  obs vs sim(masked)"),
                      ("ac1_Qobs", "ac1_Qsim", "ac1  obs vs sim(full)  ")]:
        m = d[[a, b]].dropna()
        rho = stats.spearmanr(m[a], m[b]).statistic
        r = np.corrcoef(np.log(m[a]), np.log(m[b]))[0, 1] if a.startswith("tau") else \
            np.corrcoef(m[a], m[b])[0, 1]
        print(f"  {lab}: Spearman {rho:+.3f}  Pearson(log/raw) {r:+.3f}  n={len(m)}",
              flush=True)

    print("\n=== TIMING: observed vs simulated flow ===", flush=True)
    ok = d[(d.sig_obs > 0.2) & (d.sig > 0.2)]
    print(f"catchments with a detectable signal in BOTH: {len(ok)}", flush=True)
    for a, b, lab in [("reg_lag_obs", "reg_lag", "response lag "),
                      ("late_frac_obs", "late_frac", "late fraction")]:
        m = ok[[a, b]].dropna()
        print(f"  {lab}: obs median {m[a].median():.2f}  sim median {m[b].median():.2f}  "
              f"Spearman {stats.spearmanr(m[a], m[b]).statistic:+.3f}  n={len(m)}",
              flush=True)
    m = ok[["late_frac_obs", "sp_active_frac"]].dropna()
    print(f"  observed late fraction vs snow-active fraction: Spearman "
          f"{stats.spearmanr(m.late_frac_obs, m.sp_active_frac).statistic:+.3f}", flush=True)
    snowy = ok[ok.sp_active_frac > 0.3]
    flashy = ok[ok.sp_active_frac < 0.05]
    print(f"  snow-active (>30%, n={len(snowy)}): observed reg_lag "
          f"{snowy.reg_lag_obs.median():.2f} mo, late_frac {snowy.late_frac_obs.median():.2f}",
          flush=True)
    print(f"  snow-free  (<5%,  n={len(flashy)}): observed reg_lag "
          f"{flashy.reg_lag_obs.median():.2f} mo, late_frac {flashy.late_frac_obs.median():.2f}",
          flush=True)

    # Does the INTRINSIC memory govern how long the FORCED anomaly lasts? Restricted to
    # snow-free catchments, where the lag profile is unimodal so duration and timing
    # separate; see the stage2c_registration_lag.py docstring for why that restriction
    # matters and what the two-sided alternative does instead.
    print("\n=== DURATION: does memory govern how long the forced signal lasts? ===",
          flush=True)
    for mem, lab in [("tau_Qobs", "observed tau"), ("tau_LZ", "simulated tau_LZ")]:
        if mem not in ok.columns:
            continue
        g = ok[["retention_obs", mem, "sp_active_frac"]].dropna()
        g = g[g[mem] > 0]
        free = g[g.sp_active_frac < 0.05]
        for sub, slab in [(g, "all      "), (free, "snow-free")]:
            if len(sub) < 20:
                continue
            rho = stats.spearmanr(sub.retention_obs, np.log(sub[mem])).statistic
            print(f"  {slab} n={len(sub):4d}: Spearman retention_obs vs log {lab}"
                  f" = {rho:+.3f}", flush=True)
        if len(free) >= 40:
            q = pd.qcut(free[mem], 4, labels=["Q1", "Q2", "Q3", "Q4"])
            med = free.groupby(q, observed=True).retention_obs.median()
            print(f"    snow-free retention by {lab} quartile: "
                  + ", ".join(f"{k}={v:.3f}" for k, v in med.items()), flush=True)


def selftest():
    rng = np.random.default_rng(0)
    n = 20000
    dates = pd.date_range("1970-01-01", periods=n, freq="D")

    # AR(1) with a known timescale, plus a seasonal cycle to be removed
    for phi, name in [(0.90, "fast"), (0.99, "slow")]:
        x = np.zeros(n)
        for i in range(1, n):
            x[i] = phi * x[i - 1] + rng.normal()
        seas = 3.0 * np.sin(2 * np.pi * dates.dayofyear / 365.25)
        full = pd.Series(x + seas, index=dates)
        gap = full.copy()
        gap[rng.random(n) < 0.45] = np.nan          # 45 % missing, as observed flow
        tau_full = efolding_from_acf(acf_gapaware(deseasonalize_detrend_nan(full))[0])
        tau_gap = efolding_from_acf(acf_gapaware(deseasonalize_detrend_nan(gap))[0])
        expect = -1.0 / np.log(phi)
        assert abs(tau_full - expect) < 0.25 * expect, (name, tau_full, expect)
        assert abs(tau_gap - tau_full) < 0.20 * tau_full, (name, tau_gap, tau_full)
        print(f"selftest {name}: expected tau={expect:.1f} d, complete={tau_full:.1f} d, "
              f"45%-gappy={tau_gap:.1f} d")

    # the gap-aware ACF must beat naive compaction on a gappy series
    x = np.zeros(n)
    for i in range(1, n):
        x[i] = 0.99 * x[i - 1] + rng.normal()
    gap = pd.Series(x, index=dates)
    gap[rng.random(n) < 0.45] = np.nan
    a = deseasonalize_detrend_nan(gap)
    tau_gap = efolding_from_acf(acf_gapaware(a)[0])
    compact = a[np.isfinite(a)]
    fc = np.fft.rfft(compact - compact.mean(), 1 << int(np.ceil(np.log2(2 * compact.size))))
    acf_c = np.fft.irfft(fc * np.conj(fc))[: KMAX + 1].real
    tau_compact = efolding_from_acf(acf_c / acf_c[0])
    expect = -1.0 / np.log(0.99)
    assert abs(tau_gap - expect) < abs(tau_compact - expect), (tau_gap, tau_compact, expect)
    print(f"selftest gaps: expected {expect:.1f} d, gap-aware {tau_gap:.1f} d, "
          f"naive-compaction {tau_compact:.1f} d (biased short, as expected)")

    # timing metrics recover an injected melt lag from a gappy monthly series
    years = np.arange(1960, 2020)
    phat = pd.Series(rng.normal(size=len(years)), index=years)
    didx = pd.date_range("1959-12-01", "2019-12-31", freq="D")
    q = pd.Series(rng.normal(0, 0.2, len(didx)), index=didx)
    for y, p in phat.items():
        for L, w in {1: 0.6, 7: 1.2}.items():
            dt = pd.Timestamp(int(y) - 1, 12, 1) + pd.DateOffset(months=L)
            sel = (q.index.year == dt.year) & (q.index.month == dt.month)
            q[sel] += w * p
    q[rng.random(len(q)) < 0.3] = np.nan
    r, nL = lag_profile(monthly_anom_gapaware(q), phat)
    m = timing_metrics(r, nL, "_obs")
    assert m["reg_lag_obs"] > 4.0 and m["late_frac_obs"] > 0.5, m
    # the injected response is LATE (a melt peak at L=7) but not LONG: the one-sided
    # retention window stops at L=6, so it must stay low where late_frac is high
    assert m["retention_obs"] < 0.3, m
    print(f"selftest timing (30% gappy): reg_lag={m['reg_lag_obs']:.2f} mo, "
          f"late_frac={m['late_frac_obs']:.2f}  (injected melt at L=7)")
    print("selftest OK")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--states-dir")
    ap.add_argument("--manifest")
    ap.add_argument("--stage1")
    ap.add_argument("--indices")
    ap.add_argument("--stage2")
    ap.add_argument("--stage2c")
    ap.add_argument("--out")
    ap.add_argument("--selftest", action="store_true")
    a = ap.parse_args()
    if a.selftest:
        selftest()
        return
    need = [a.states_dir, a.manifest, a.stage1, a.indices, a.stage2, a.stage2c, a.out]
    if not all(need):
        ap.error("--states-dir --manifest --stage1 --indices --stage2 --stage2c --out "
                 "required unless --selftest")
    stage1 = pd.read_parquet(a.stage1)
    indices = pd.read_csv(a.indices).set_index("winter_year")
    res = run(a.states_dir, a.manifest, stage1, indices)
    res.to_parquet(a.out)
    print(f"wrote {a.out}  ({len(res)} catchments)", flush=True)
    validate(res, pd.read_parquet(a.stage2), pd.read_parquet(a.stage2c))


if __name__ == "__main__":
    main()
